// This file was generated by Prisma, and assumes you have installed the followinpnpg:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // @ts-expect-error nothing
    url: process.env['POSTGRES_URL'],
  },
});
